In [ ]:
import pandas as pd
import os
from six.moves import urllib
import mysql.connector as connection

In [2]:
download_dir = "./data/"

os.makedirs(download_dir, exist_ok=True)

download_url = "https://raw.githubusercontent.com/mohitmahiyt/bank_dataset/main/bank.csv"

filename = os.path.basename(download_url)
print(filename)

download_file_path = os.path.join(download_dir,filename)
\
print(download_file_path)

urllib.request.urlretrieve(download_url, download_file_path)

bank.csv
./data/bank.csv

('./data/bank.csv', <http.client.HTTPMessage at 0x1d88e0d30d0>)

In [3]:
df=pd.read_csv(download_file_path, delimiter=";")

In [4]:

df.to_csv('cleaned_data.csv')

In [5]:
conn=connection.connect(password='2616',username='root')

In [6]:
list(df.iterrows())

[(0,
  age                  30
  job          unemployed
  marital         married
  education       primary
  default              no
  balance            1787
  housing              no
  loan                 no
  contact        cellular
  day                  19
  month               oct
  duration             79
  campaign              1
  pdays                -1
  previous              0
  poutcome        unknown
  y                    no
  Name: 0, dtype: object),
 (1,
  age                 33
  job           services
  marital        married
  education    secondary
  default             no
  balance           4789
  housing            yes
  loan               yes
  contact       cellular
  day                 11
  month              may
  duration           220
  campaign             1
  pdays              339
  previous             4
  poutcome       failure
  y                   no
  Name: 1, dtype: object),
 (2,
  age                  35
  job          management
  marital          single
  education      tertiary
  default              no
  balance            1350
  housing             yes
  loan                 no
  contact        cellular
  day                  16
  month               apr
  duration            185
  campaign              1
  pdays               330
  previous              1
  poutcome        failure
  y                    no
  Name: 2, dtype: object),
 (3,
  age                  30
  job          management
  marital         married
  education      tertiary
  default              no
  balance            1476
  housing             yes
  loan                yes
  contact         unknown
  day                   3
  month               jun
  duration            199
  campaign              4
  pdays                -1
  previous              0
  poutcome        unknown
  y                    no
  Name: 3, dtype: object),
 (4,
  age                   59
  job          blue-collar
  marital          married
  education      secondary
  default               no
  balance                0
  housing              yes
  loan                  no
  contact          unknown
  day                    5
  month                may
  duration             226
  campaign               1
  pdays                 -1
  previous               0
  poutcome         unknown
  y                     no
  Name: 4, dtype: object),
 (5,
  age                  35
  job          management
  marital          single
  education      tertiary
  default              no
  balance             747
  housing              no
  loan                 no
  contact        cellular
  day                  23
  month               feb
  duration            141
  campaign              2
  pdays               176
  previous              3
  poutcome        failure
  y                    no
  Name: 5, dtype: object),
 (6,
  age                     36
  job          self-employed
  marital            married
  education         tertiary
  default                 no
  balance                307
  housing                yes
  loan                    no
  contact           cellular
  day                     14
  month                  may
  duration               341
  campaign                 1
  pdays                  330
  previous                 2
  poutcome             other
  y                       no
  Name: 6, dtype: object),
 (7,
  age                  39
  job          technician
  marital         married
  education     secondary
  default              no
  balance             147
  housing             yes
  loan                 no
  contact        cellular
  day                   6
  month               may
  duration            151
  campaign              2
  pdays                -1
  previous              0
  poutcome        unknown
  y                    no
  Name: 7, dtype: object),
 (8,
  age                    41
  job          entrepreneur
  marital           married
  education        tertiary
  default                no
  balance               221
  housing               yes
  loan                   no
  contact           unknown
  day                    14
  month                 may
  duration               57
  campaign                2
  pdays                  -1
  previous                0
  poutcome          unknown
  y                      no
  Name: 8, dtype: object),
 (9,
  age                43
  job          services
  marital       married
  education     primary
  default            no
  balance           -88
  housing           yes
  loan              yes
  contact      cellular
  day                17
  month             apr
  duration          313
  campaign            1
  pdays             147
  previous            2
  poutcome      failure
  y                  no
  Name: 9, dtype: object),
 (10,
  age                 39
  job           services
  marital        married
  education    secondary
  default             no
  balance           9374
  housing            yes
  loan                no
  contact        unknown
  day                 20
  month              may
  duration           273
  campaign             1
  pdays               -1
  previous             0
  poutcome       unknown
  y                   no
  Name: 10, dtype: object),
 (11,
  age                 43
  job             admin.
  marital        married
  education    secondary
  default             no
  balance            264
  housing            yes
  loan                no
  contact       cellular
  day                 17
  month              apr
  duration           113
  campaign             2
  pdays               -1
  previous             0
  poutcome       unknown
  y                   no
  Name: 11, dtype: object),
 (12,
  age                  36
  job          technician
  marital         married
  education      tertiary
  default              no
  balance            1109
  housing              no
  loan                 no
  contact        cellular
  day                  13
  month               aug
  duration            328
  campaign              2
  pdays                -1
  previous              0
  poutcome        unknown
  y                    no
  Name: 12, dtype: object),
 (13,
  age                 20
  job            student
  marital         single
  education    secondary
  default             no
  balance            502
  housing             no
  loan                no
  contact       cellular
  day                 30
  month              apr
  duration           261
  campaign             1
  pdays               -1
  previous             0
  poutcome       unknown
  y                  yes
  Name: 13, dtype: object),
 (14,
  age                   31
  job          blue-collar
  marital          married
  education      secondary
  default               no
  balance              360
  housing              yes
  loan                 yes
  contact         cellular
  day                   29
  month                jan
  duration              89
  campaign               1
  pdays                241
  previous               1
  poutcome         failure
  y                     no
  Name: 14, dtype: object),
 (15,
  age                  40
  job          management
  marital         married
  education      tertiary
  default              no
  balance             194
  housing              no
  loan                yes
  contact        cellular
  day                  29
  month               aug
  duration            189
  campaign              2
  pdays                -1
  previous              0
  poutcome        unknown
  y                    no
  Name: 15, dtype: object),
 (16,
  age                  56
  job          technician
  marital         married
  education     secondary
  default              no
  balance            4073
  housing              no
  loan                 no
  contact        cellular
  day                  27
  month               aug
  duration            239
  campaign              5
  pdays                -1
  previous              0
  poutcome        unknown
  y                    no
  Name: 16, dtype: object),
 (17,
  age                37
  job            admin.
  marital        single
  education    tertiary
  default            no
  balance          2317
  housing           yes
  loan               no
  contact      cellular
  day                20
  month             apr
  duration          114
  campaign            1
  pdays             152
  previous            2
  poutcome      failure
  y                  no
  Name: 17, dtype: object),
 (18,
  age                   25
  job          blue-collar
  marital           single
  education        primary
  default               no
  balance             -221
  housing              yes
  loan                  no
  contact          unknown
  day                   23
  month                may
  duration             250
  campaign               1
  pdays                 -1
  previous               0
  poutcome         unknown
  y                     no
  Name: 18, dtype: object),
 (19,
  age                 31
  job           services
  marital        married
  education    secondary
  default             no
  balance            132
  housing             no
  loan                no
  contact       cellular
  day                  7
  month              jul
  duration           148
  campaign             1
  pdays              152
  previous             1
  poutcome         other
  y                   no
  Name: 19, dtype: object),
 (20,
  age                  38
  job          management
  marital        divorced
  education       unknown
  default              no
  balance               0
  housing             yes
  loan                 no
  contact        cellular
  day                  18
  month               nov
  duration             96
  campaign              2
  pdays                -1
  previous              0
  poutcome        unknown
  y                    no
  Name: 20, dtype: object),
 (21,
  age                  42
  job          management
  marital        divorced
  education      tertiary
  default              no
  balance              16
  housing              no
  loan                 no
  contact        cellular
  day                  19
  month               nov
  duration            140
  campaign              3
  pdays                -1
  previous              0
  poutcome        unknown
  y                    no
  Name: 21, dtype: object),
 (22,
  age                 44
  job           services
  marital         single
  education    secondary
  default             no
  balance            106
  housing             no
  loan                no
  contact        unknown
  day                 12
  month              jun
  duration           109
  campaign             2
  pdays               -1
  previous             0
  poutcome       unknown
  y                   no
  Name: 22, dtype: object),
 (23,
  age                    44
  job          entrepreneur
  marital           married
  education       secondary
  default                no
  balance                93
  housing                no
  loan                   no
  contact          cellular
  day                     7
  month                 jul
  duration              125
  campaign                2
  pdays                  -1
  previous                0
  poutcome          unknown
  y                      no
  Name: 23, dtype: object),
 (24,
  age                 26
  job          housemaid
  marital        married
  education     tertiary
  default             no
  balance            543
  housing             no
  loan                no
  contact       cellular
  day                 30
  month              jan
  duration           169
  campaign             3
  pdays               -1
  previous             0
  poutcome       unknown
  y                   no
  Name: 24, dtype: object),
 (25,
  age                  41
  job          management
  marital         married
  education      tertiary
  default              no
  balance            5883
  housing              no
  loan                 no
  contact        cellular
  day                  20
  month               nov
  duration            182
  campaign              2
  pdays                -1
  previous              0
  poutcome        unknown
  y                    no
  Name: 25, dtype: object),
 (26,
  age                   55
  job          blue-collar
  marital          married
  education        primary
  default               no
  balance              627
  housing              yes
  loan                  no
  contact          unknown
  day                    5
  month                may
  duration             247
  campaign               1
  pdays                 -1
  previous               0
  poutcome         unknown
  y                     no
  Name: 26, dtype: object),
 (27,
  age                 67
  job            retired
  marital        married
  education      unknown
  default             no
  balance            696
  housing             no
  loan                no
  contact      telephone
  day                 17
  month              aug
  duration           119
  campaign             1
  pdays              105
  previous             2
  poutcome       failure
  y                   no
  Name: 27, dtype: object),
 (28,
  age                     56
  job          self-employed
  marital            married
  education        secondary
  default                 no
  balance                784
  housing                 no
  loan                   yes
  contact           cellular
  day                     30
  month                  jul
  duration               149
  campaign                 2
  pdays                   -1
  previous                 0
  poutcome           unknown
  y                       no
  Name: 28, dtype: object),
 (29,
  age                 53
  job             admin.
  marital        married
  education    secondary
  default             no
  balance            105
  housing             no
  loan               yes
  contact       cellular
  day                 21
  month              aug
  duration            74
  campaign             2
  pdays               -1
  previous             0
  poutcome       unknown
  y                   no
  Name: 29, dtype: object),
 (30,
  age                 68
  job            retired
  marital       divorced
  education    secondary
  default             no
  balance           4189
  housing             no
  loan                no
  contact      telephone
  day                 14
  month              jul
  duration           897
  campaign             2
  pdays               -1
  previous             0
  poutcome       unknown
  y                  yes
  Name: 30, dtype: object),
 (31,
  age                  31
  job          technician
  marital         married
  education     secondary
  default              no
  balance             171
  housing              no
  loan                 no
  contact        cellular
  day                  27
  month               aug
  duration             81
  campaign              3
  pdays                -1
  previous              0
  poutcome        unknown
  y                    no
  Name: 31, dtype: object),
 (32,
  age                  59
  job          management
  marital         married
  education     secondary
  default              no
  balance              42
  housing              no
  loan                 no
  contact        cellular
  day                  21
  month               nov
  duration             40
  campaign              1
  pdays                -1
  previous              0
  poutcome        unknown
  y                    no
  Name: 32, dtype: object),
 (33,
  age                  32
  job          management
  marital          single
  education      tertiary
  default              no
  balance            2536
  housing             yes
  loan                 no
  contact        cellular
  day                  26
  month               aug
  duration            958
  campaign              6
  pdays                -1
  previous              0
  poutcome        unknown
  y                   yes
  Name: 33, dtype: object),
 (34,
  age                  49
  job          technician
  marital         married
  education      tertiary
  default              no
  balance            1235
  housing              no
  loan                 no
  contact        cellular
  day                  13
  month               aug
  duration            354
  campaign              3
  pdays                -1
  previous              0
  poutcome        unknown
  y                   yes
  Name: 34, dtype: object),
 (35,
  age                 42
  job             admin.
  marital       divorced
  education    secondary
  default             no
  balance           1811
  housing            yes
  loan                no
  contact        unknown
  day                 14
  month              may
  duration           150
  campaign             1
  pdays               -1
  previous             0
  poutcome       unknown
  y                   no
  Name: 35, dtype: object),
 (36,
  age                 78
  job            retired
  marital       divorced
  education      primary
  default             no
  balance            229
  housing             no
  loan                no
  contact      telephone
  day                 22
  month              oct
  duration            97
  campaign             1
  pdays               -1
  previous             0
  poutcome       unknown
  y                  yes
  Name: 36, dtype: object),
 (37,
  age                   32
  job          blue-collar
  marital          married
  education      secondary
  default               no
  balance             2089
  housing              yes
  loan                  no
  contact         cellular
  day                   14
  month                nov
  duration             132
  campaign               1
  pdays                 -1
  previous               0
  poutcome         unknown
  y                    yes
  Name: 37, dtype: object),
 (38,
  age                  33
  job          management
  marital         married
  education     secondary
  default              no
  balance            3935
  housing             yes
  loan                 no
  contact        cellular
  day                   6
  month               may
  duration            765
  campaign              1
  pdays               342
  previous              2
  poutcome        failure
  y                   yes
  Name: 38, dtype: object),
 (39,
  age                23
  job          services
  marital        single
  education    tertiary
  default            no
  balance           363
  housing           yes
  loan               no
  contact       unknown
  day                30
  month             may
  duration           16
  campaign           18
  pdays              -1
  previous            0
  poutcome      unknown
  y                  no
  Name: 39, dtype: object),
 (40,
  age                  38
  job          management
  marital          single
  education      tertiary
  default              no
  balance           11971
  housing             yes
  loan                 no
  contact         unknown
  day                  17
  month               nov
  duration            609
  campaign              2
  pdays               101
  previous              3
  poutcome        failure
  y                    no
  Name: 40, dtype: object),
 (41,
  age                  36
  job          management
  marital          single
  education      tertiary
  default              no
  balance             553
  housing              no
  loan                 no
  contact        cellular
  day                  11
  month               aug
  duration            106
  campaign              2
  pdays                -1
  previous              0
  poutcome        unknown
  y                    no
  Name: 41, dtype: object),
 (42,
  age                   52
  job          blue-collar

In [7]:
try:
    conn=connection.connect(password='2616',user='root', database= "bank_db")
    
    for key, value in df.iterrows():
        age = value[0]
        job = value[1]
        marital= value[2]
        education = value[3]
        default = value[4]
        balance= value[5] 
        housing=value[6]
        loan=value[7] 
        contact=value[8] 
        day=value[9] 
        month=value[10] 
        duration=value[11] 
        campaign=value[12] 
        pdays=value[13]
        previous=value[14] 
        poutcome=value[15] 
        y=value[16]
        
        query = f"""insert into bank_details values ({age},'{job}', '{marital}','{education}','{default}',{balance},'{housing}','{loan}','{contact}',{day},'{month}',
        {duration},{campaign},{pdays},{previous},'{poutcome}','{y}');"""
        cursor = conn.cursor()
        cursor.execute(query)
        conn.commit()
except Exception as e:
    print(e)
else:
    print("records inserted successfully")
finally:
    conn.close()

C:\Users\kajol\AppData\Local\Temp\ipykernel_8424\12039862.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  age = value[0]
C:\Users\kajol\AppData\Local\Temp\ipykernel_8424\12039862.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  job = value[1]
C:\Users\kajol\AppData\Local\Temp\ipykernel_8424\12039862.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  marital= value[2]
C:\Users\kajol\AppData\Local\Temp\ipykernel_8424\12039862.py:8: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  education = value[3]
C:\Users\kajol\AppData\Local\Temp\ipykernel_8424\12039862.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  default = value[4]
C:\Users\kajol\AppData\Local\Temp\ipykernel_8424\12039862.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  balance= value[5]
C:\Users\kajol\AppData\Local\Temp\ipykernel_8424\12039862.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  housing=value[6]
C:\Users\kajol\AppData\Local\Temp\ipykernel_8424\12039862.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  loan=value[7]
C:\Users\kajol\AppData\Local\Temp\ipykernel_8424\12039862.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  contact=value[8]
C:\Users\kajol\AppData\Local\Temp\ipykernel_8424\12039862.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  day=value[9]
C:\Users\kajol\AppData\Local\Temp\ipykernel_8424\12039862.py:15: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  month=value[10]
C:\Users\kajol\AppData\Local\Temp\ipykernel_8424\12039862.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  duration=value[11]
C:\Users\kajol\AppData\Local\Temp\ipykernel_8424\12039862.py:17: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  campaign=value[12]
C:\Users\kajol\AppData\Local\Temp\ipykernel_8424\12039862.py:18: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  pdays=value[13]
C:\Users\kajol\AppData\Local\Temp\ipykernel_8424\12039862.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  previous=value[14]
C:\Users\kajol\AppData\Local\Temp\ipykernel_8424\12039862.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  poutcome=value[15]
C:\Users\kajol\AppData\Local\Temp\ipykernel_8424\12039862.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  y=value[16]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        4521 non-null   int64
 1   job        4521 non-null   object
 2   marital    4521 non-null   object
 3   education  4521 non-null   object
 4   default    4521 non-null   object
 5   balance    4521 non-null   int64
 6   housing    4521 non-null   object
 7   loan       4521 non-null   object
 8   contact    4521 non-null   object
 9   day        4521 non-null   int64
 10  month      4521 non-null   object
 11  duration   4521 non-null   int64
 12  campaign   4521 non-null   int64
 13  pdays      4521 non-null   int64
 14  previous   4521 non-null   int64
 15  poutcome   4521 non-null   object
 16  y          4521 non-null   object
dtypes: int64(7), object(10)
memory usage: 600.6+ KB